import {
  g1,
  g2,
  g3,
  g4,
  g5,
  g6,
  g7,
  g8,
  g9,
  g10,
  g11,
} from "./assets/gallery/index";
export default [
  { id: 0, cluster: 1, src: g1 },
  { id: 1, cluster: 1, src: g2 },
  { id: 2, cluster: 1, src: g3 },
  { id: 3, cluster: 1, src: g4 },
  { id: 4, cluster: 1, src: g5 },
  { id: 5, cluster: 1, src: g6 },
  { id: 6, cluster: 1, src: g7 },
  { id: 7, cluster: 1, src: g8 },
  { id: 8, cluster: 1, src: g9 },
  { id: 9, cluster: 1, src: g10 },
  { id: 10, cluster: 1, src: g11 },
];
